### ISSUE TITLE
how can i bring my origin at (0,0) , i.e how can i start my horizontal line from origin instead of negative 

### ISSUE THREAD

**Issue by firdousalam** [ryanrolds/quiche#10]
![capturequiche](https://user-images.githubusercontent.com/11075031/29517099-024f48ba-8691-11e7-8c6b-3539edab94b5.PNG)
how can i bring my origin at (0,0) , i.e how can i start my horizontal line from origin instead of negative for Graph containing negative values

**Comment by ryanrolds** [comment]
Good question. I will look in to this and get back to you later today.

**Comment by ryanrolds** [comment]
I looked through Google's Image Charts API and I don't see a way to adjust the chart. Removing any negative values, or changing them to 0, would correct the issue.

**Comment by ryanrolds** [comment]
Added setAxisRange(axis ["x", "r", "y"], start [number], end [number], step [number]) to line and bar charts. It should do what you need. The function will also set the data scale so that the labels and data match.

This is in version 0.3.0, which was just published. See https://github.com/ryanrolds/quiche/blob/master/test/line.range.test.js#L13 for usage example.
